version: "3.4"

services:
  unbound:
    build: .
    restart: always
    ports:
      - "${EXTERNALIP}:53:1053"
      - "${EXTERNALIP}:53:1053/udp"
      - "127.0.0.1:53:1053"
      - "127.0.0.1:53:1053/udp"
        #    network_mode: "host"
        #    privileged: true
